# Generated by Django 4.1 on 2023-11-19 22:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0002_rename_datedcompleted_task_datecompleted'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_usuario', models.CharField(choices=[('Paciente', 'Paciente'), ('Administrador', 'Administrador'), ('Medico', 'Medico'), ('Secretaria', 'Secretaria'), ('Cajero', 'Cajero')], max_length=50, verbose_name='Tipo de usuario')),
                ('rut', models.CharField(max_length=20, verbose_name='RUT')),
                ('direccion', models.CharField(max_length=400, verbose_name='Dirección')),
                ('imagen', models.ImageField(upload_to='perfiles/', verbose_name='Imagen')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
