# Generated by Django 4.1 on 2023-11-19 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_perfil_delete_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(upload_to='tasks/media/perfiles', verbose_name='Imagen'),
        ),
    ]
