# Generated by Django 4.1 on 2023-11-19 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_perfil_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='imagen',
            field=models.ImageField(upload_to='perfiles/', verbose_name='Imagen'),
        ),
    ]
